env: "gymma"
common_reward: True
reward_scalarisation: "sum"
env_args:
  key: null
  time_limit: 200
  seed: 1

seed: 1
batch_size_run: 4
batch_size: 4
buffer_size: 4
gamma: 0.99
lr: 0.0005
grad_norm_clip: 10
target_update_interval_or_tau: 0.01
epochs: 4
add_value_last_step: True

hidden_dim: 64
obs_agent_id: True
obs_last_action: False
obs_individual_obs: False
use_rnn: True
standardise_returns: False
standardise_rewards: True

runner: "parallel"
t_max: 2000000
test_nepisode: 20
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
use_cuda: True
buffer_cpu_only: True

save_model: False
save_model_interval: 50000
checkpoint_path: ""
evaluate: False
render: False
load_step: 0
save_replay: False
use_tensorboard: False
local_results_path: "results"