name: "maa2c"
learner: "actor_critic_learner"
critic_type: "cv_critic"

agent_output_type: "pi_logits"
action_selector: "soft_policies"
mask_before_softmax: True

entropy_coef: 0.01

buffer_size: 10
batch_size_run: 10
batch_size: 10
lr: 0.0005
hidden_dim: 128
target_update_interval_or_tau: 0.01
q_nstep: 5

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

t_max: 20050000