env: "gymma"

common_reward: True
reward_scalarisation: "sum"

env_args:
  key: "rware:rware-tiny-2ag-v2"
  time_limit: 500
  seed: 42

test_greedy: True
test_nepisode: 20
test_interval: 50000

log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000

t_max: 2050000